import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import '@/app/shared/fonts/fonts.css'
import {NavBar} from "@/app/widgets";


export const metadata: Metadata = {
  title: "Verbitsky | Дизайн интерьера",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
