import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import '@/app/shared/fonts/fonts.css'


export const metadata: Metadata = {
  title: "Verbitsky | Дизайн интерьера",
  description: "Generated by create next app",
};
import { SpeedInsights } from "@vercel/speed-insights/next"
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <SpeedInsights/>
      <body>
        {children}
      </body>
    </html>
  );
}
